version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    volumes:
      - ./nearbuy_db/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data

  server:
    build: ./nearbuy_server
    env_file:
      - ./.env
    environment:
      - port=${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./nearbuy_server/src:/app/src
    depends_on:
      - postgres

  vue:
    build: ./nearbuy_vue
    env_file:
      - ./nearbuy_vue/.env
    environment:
      - port=${VITE_PORT}
    ports:
      - ${VITE_PORT}:${VITE_PORT}
    volumes:
      - ./nearbuy_vue/src:/app/src
    depends_on:
      - server

volumes:
  pgdata:
